{{- if and .Values.global.environment (eq .Values.global.environment "openshift") }}

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: edge
  namespace: {{ .Release.Namespace }}
spec:
  host: 
  {{- if .Values.global.remove_namespace_from_url }}
    {{ tpl .Values.ingress_config.custom_url . }}
  {{- else }}
    {{ tpl .Values.ingress_config.default_url . }}
  {{- end }}
  port: 
    targetPort: http
  tls:
    termination: passthrough
  to:
    kind: Service
    name: edge
    weight: 100
  wildcardPolicy: None

{{- else }}

apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: edge
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - host: {{ if .Values.global.remove_namespace_from_url -}}
    {{ tpl .Values.ingress_config.custom_url . }}
  {{- else }}
    {{- tpl .Values.ingress_config.default_url . }}
  {{- end }}
    tcp:
      port: '443'
      backend:
        serviceName: edge
        servicePort: 8443
{{- end }}