global:
  environment: kubernetes
  domain: 
  route_url_name: 
  remove_namespace_from_url: ''
  exhibitor:
    replicas: 1
  xds:
    port: 18000
    cluster: greymatter

test:
  catalog_sidecar:
    zk_announce_path: /services/catalog-sidecar-test/1.0/
  catalog:
  documentation:


sidecar:
  version: 0.7.1
  image: 'docker.production.deciphernow.com/deciphernow/gm-proxy:0.7.1'
  imagePullPolicy: Always
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  envvars:
  - type: value
    name: ingres_use_tls
    value: 'true'
  - type: value
    name: ingress_ca_cert_path
    value: '/etc/proxy/tls/sidecar/ca.crt'
  - type: value
    name: ingress_cert_path
    value: '/etc/proxy/tls/sidecar/server.crt'
  - type: value
    name: ingress_key_path
    value: '/etc/proxy/tls/sidecar/server.key'
  - type: value
    name: metrics_key_function
    value: 'depth'
  - type: value
    name: metrics_port
    value: "8081"
  - type: value
    name: port
    value: "9080"
  - type: value
    name: proxy_dynamic
    value: 'true'
  - type: value
    name: service_port
    value: "8080"
  - type: value
    name: service_host
    value: "127.0.0.1"
    
  # Set this to true if you are attempting to deploy Catalog by itself.
  # Ideally, catalog is deployed as a dependency to Grey Matter, which creates the
  # sidecar secret, but if individual testing is being done, the sidecar secret will
  # need to be created.
  create_sidecar_secret: false
  certificates:
    name: sidecar
    ca: |-
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
    cert: |-
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
    key: |-
      -----BEGIN RSA PRIVATE KEY-----
      ...
      -----END RSA PRIVATE KEY-----